name: build-macos-arm64

on:
  push:
    branches: [ main ]
    tags: [ 'R*' ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: macOS arm64 (static LLVM)
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          brew install meson ninja pkg-config llvm vapoursynth zstd

      - name: Set environment variables
        run: |
          echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

      - name: Show tool versions
        run: |
          clang --version || true
          g++ --version || true
          meson --version
          ninja --version
          llvm-config --version
          pkg-config --version

      - name: Check LLVM version (>= 20)
        run: |
          set -e
          ver=$(llvm-config --version | cut -d. -f1)
          if [ "$ver" -lt 20 ]; then
            echo "LLVM >= 20 is required, found: $(llvm-config --version)" >&2
            exit 1
          fi

      - name: Configure (Meson)
        run: |
          export CPATH="/opt/homebrew/include"
          export LIBRARY_PATH="/opt/homebrew/lib"
          meson setup builddir \
            -Dstatic-llvm=true \
            --buildtype=release

      - name: Build
        run: |
          export CPATH="/opt/homebrew/include"
          export LIBRARY_PATH="/opt/homebrew/lib"
          ninja -C builddir

      - name: Install to staging dir
        run: |
          DESTDIR="$PWD/stage" meson install -C builddir
          find stage -maxdepth 5 -type f -print

      - name: Collect artifact
        id: collect
        run: |
          set -e
          dll=$(find stage -type f -name 'libllvmexpr.dylib' | head -n 1)
          if [ -z "$dll" ]; then
            echo "libllvmexpr.dylib not found in install tree" >&2
            exit 1
          fi
          outdir=artifact
          mkdir -p "$outdir"
          cp "$dll" "$outdir/libllvmexpr.dylib"
          cp LICENSE "$outdir/" || true
          cp README.md "$outdir/" || true
          cp -r exprutils/ "$outdir/" || true
          cp pyproject.toml "$outdir/" || true
          echo "artifact_dir=$outdir" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: llvmexpr-macos-arm64-static-llvm20
          path: ${{ steps.collect.outputs.artifact_dir }}
          if-no-files-found: error

      - name: Create zip for release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd "${{ steps.collect.outputs.artifact_dir }}"
          zip -9r ../llvmexpr-macos-arm64-static-llvm20.zip .

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: llvmexpr-macos-arm64-static-llvm20.zip
